# Generated by Django 4.1.2 on 2022-11-13 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capswebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='block',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='email',
            field=models.EmailField(blank=True, max_length=60, validators=[django.core.validators.RegexValidator(message='Email must be: @plm.edu.ph', regex='^[A-Za-z0-9._%+-]+@plm.edu.ph$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='numberID',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Faculty ID must be entered in format: 20XXXXXXX', regex='^20\\d{7}$')], verbose_name='Number ID'),
        ),
    ]
